blank_issues_enabled: false
contact_links:
  - name: Request a Feature
    url: https://github.com/CairnCMS/cairncms/discussions
    about: Share your ideas on how to make CairnCMS better.
  - name: Ask a Question
    url: https://github.com/CairnCMS/cairncms/discussions
    about: Please ask and answer questions here.
